# Generated by Django 3.2.7 on 2021-09-04 22:56

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nickname', models.CharField(max_length=100, verbose_name='Nickname')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
                ('icone', models.CharField(choices=[('bi bi-instagram', 'Instagram'), ('bi bi-facebook', 'Facebook'), ('bi bi-twitter', 'Twitter'), ('bi bi-youtube', 'Youtube'), ('bi bi-whatsapp', 'Whatsapp')], max_length=17, verbose_name='Icone')),
                ('imagem', stdimage.models.StdImageField(upload_to='link', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
